name: ReplantCropCount
version: 1.0.0
main: kr.argonaut.replantCropCount.ReplantCropCountPlugin
description: 자동심기 플러그인 with Kotlin
author: RookieAND
website: https://github.com/RookieAND
api-version: '1.20'